"""Opt-in VM integration check; supply a panel generated by prepareSensitivity.

This is separate from pytest because it loads all private deployed checkpoints.
Use the documented public reference example; do not publish private input/results.
"""
import argparse
import json
from pathlib import Path
import time
import torch
from offtargetpred.inference import InferenceEngine
from offtargetpred.input_metadata import normalize_input_metadata
from offtargetpred.sequence import parse_pairs

parser = argparse.ArgumentParser()
parser.add_argument("--submission", type=Path, required=True)
parser.add_argument("--models", type=Path, required=True)
parser.add_argument("--source-document", type=Path, required=True)
parser.add_argument("--source-row", type=int, default=2, help="Zero-based source document row")
parser.add_argument("--output-directory", type=Path, required=True)
args = parser.parse_args()
submission = json.loads(args.submission.read_text())
source = json.loads(args.source_document.read_text())["rows"][args.source_row]
rows = normalize_input_metadata(parse_pairs(submission["input"], "csv"))
assert len(rows) == 61
assert rows[0]["target"] == source["target"] and rows[0]["off_target"] == source["off_target"]
assert all(not any(key in row for key in ("assembly", "chromosome", "start", "end", "user_selected_locus")) for row in rows)
torch.set_num_threads(2)
engine = InferenceEngine(args.models, device="cuda")
start = time.monotonic()
first = engine.score(rows, ["k1", "k2", "k3"])
repeat = engine.score(rows, ["k1", "k2", "k3"])
report = {"candidate_pairs": len(rows), "device": torch.cuda.get_device_name(0), "seconds": time.monotonic() - start, "models": {}}
for model in ("k1", "k2", "k3"):
    maximum = max(abs(a["scores"][model] - b["scores"][model]) for a, b in zip(first, repeat))
    baseline_diff = abs(first[0]["scores"][model] - source["scores"][model])
    assert maximum <= 1e-6, (model, maximum)
    assert baseline_diff <= 1e-4, (model, baseline_diff)
    deltas = [row["scores"][model] - first[0]["scores"][model] for row in first[1:]]
    report["models"][model] = {"original_score": first[0]["scores"][model], "repeat_max_abs_diff": maximum, "frozen_original_abs_diff": baseline_diff, "delta_min": min(deltas), "delta_max": max(deltas)}
args.output_directory.mkdir(parents=True, exist_ok=True)
(args.output_directory / "sensitivity-results.json").write_text(json.dumps({"rows": first, "metadata": {"mode": "pairs", "models": engine.metadata(), "scope": "Synthetic single-base model-response software verification"}}, indent=2))
(args.output_directory / "sensitivity-check.json").write_text(json.dumps(report, indent=2))
print(json.dumps(report, indent=2))
