import type { Credentials } from "../api";

// Match the UUID and token_urlsafe(32) capability generated by jobs.py.
const jobId = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/;
const jobToken = /^[A-Za-z0-9_-]{43}$/;

/** Accept only server-generated capability shapes, including values from storage. */
export function validateRecoveryCredentials(value: unknown): Credentials | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) return null;
  const { id, token } = value as Record<string, unknown>;
  return typeof id === "string" && jobId.test(id) && typeof token === "string" && jobToken.test(token)
    ? { id, token }
    : null;
}

/** Duplicate credentials are ambiguous and must not silently select a private job. */
export function parseRecoveryFragment(fragment: string): Credentials | null {
  const params = new URLSearchParams(fragment.replace(/^#/, ""));
  if (params.getAll("job").length !== 1 || params.getAll("token").length !== 1) return null;
  if ([...params.keys()].some(key => key !== "job" && key !== "token")) return null;
  return validateRecoveryCredentials({ id: params.get("job"), token: params.get("token") });
}

/** Preserve a GitHub Pages subdirectory while removing all prior query/hash data. */
export function privateJobLink(currentUrl: string, credentials: Credentials): string {
  if (!validateRecoveryCredentials(credentials)) throw new Error("Invalid private job credentials.");
  const url = new URL(currentUrl);
  if (url.protocol !== "https:" && url.protocol !== "http:") throw new Error("A web address is required for job recovery.");
  url.username = "";
  url.password = "";
  url.search = "";
  url.hash = new URLSearchParams({ job: credentials.id, token: credentials.token }).toString();
  return url.toString();
}

/** Missing permission, insecure contexts and clipboard rejection all permit manual copy. */
export async function copyRecoveryLink(
  link: string,
  clipboard?: Pick<Clipboard, "writeText">,
): Promise<boolean> {
  try {
    if (!clipboard || typeof clipboard.writeText !== "function") return false;
    await clipboard.writeText(link);
    return true;
  } catch {
    return false;
  }
}
